name = "site-visitor-notifier"
main = "worker.js"
compatibility_date = "2026-09-30"

[vars]
ALLOWED_ORIGINS = "https://rbtworkdev-droid.github.io,https://orange-doodle-9q759xp4pgpcxw4-8000.app.github.dev"
TELEGRAM_CHAT_ID = "964828492"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 10, period = 60 }